// constants/tile-options.ts

export const TILE_CATEGORIES = [
  { value: "LIVING_ROOM", label: "Living Room" },
  { value: "TV_UNIT", label: "TV Unit" },
  { value: "FOYER", label: "Foyer" },
  { value: "KITCHEN", label: "Kitchen" },
  { value: "DIGITAL_WALL_TILE_CONCEPT", label: "Digital Wall Tile Concept" },
  { value: "KITCHEN_CUP_N_SAUCER_THEME", label: "Kitchen Cup N Saucer Theme" },
  { value: "GLASS_BORDERS", label: "Glass Borders" },
  { value: "RUSTIC_MATT_FLOOR_TILE", label: "Rustic Matt Floor Tile" },
  { value: "SWIMMING_POOL_MOSAICS", label: "Swimming Pool Mosaics" },
  { value: "HI_GLOSS_VITRIFIED_TILES", label: "Hi Gloss Vitrified Tiles" },
  { value: "END_MATCH_TILE", label: "End Match Tile" },
  { value: "VITRIFIED_COUNTERTOPS", label: "Vitrified Countertops" },
  { value: "T3D_TILES", label: "3D Tiles" },
  { value: "TERRAZZO_TILES", label: "Terrazzo Tiles" },
  { value: "BORDER_TILES", label: "Border Tiles" },
  { value: "COOL_TILES", label: "Cool Tiles" },
  { value: "VENKATESWARA_TILES_AND_STONES", label: "Venkateswara Tiles And Stones" },
  { value: "TEXTURED_TILES", label: "Textured Tiles" },
  { value: "PARKING_TILES", label: "Parking Tiles" },
  { value: "BALCONY", label: "Balcony" },
  { value: "BATHROOM", label: "Bathroom" },
  { value: "BEDROOM", label: "Bedroom" },
  { value: "POOJA_ROOM", label: "Pooja Room" },
  { value: "ELEVATION_TILES", label: "Elevation Tiles" },
  { value: "MOSAIC_TILES", label: "Mosaic Tiles" },
  { value: "GEOMETRIC_TILES", label: "Geometric Tiles" },
  { value: "ANTI_SKID_TILES", label: "Anti Skid Tiles" },
  { value: "SUBWAY_TILES", label: "Subway Tiles" },
  { value: "DOUBLE_CHARGE_VITRIFIED", label: "Double Charge Vitrified" },
  { value: "GLAZED_VITRIFIED", label: "Glazed Vitrified" },
  { value: "PLAIN_COLOR_TILES", label: "Plain Color Tiles" },
  { value: "U_PROFILE", label: "U Profile" },
  { value: "T_PROFILE", label: "T Profile" },
  { value: "MARBLE_TILES", label: "Marble Tiles" },
  { value: "GOD_PICTURES", label: "God Pictures" },
  { value: "ATHANGUDI_TILES", label: "Athangudi Tiles" },
  { value: "STEP_TILES", label: "Step Tiles" },
  { value: "METAL_BEADING", label: "Metal Beading" },
  { value: "GVT_STEP", label: "GVT Step" },
  { value: "POSTER_WALL_TILE", label: "Poster Wall Tile" },
  { value: "KRISHNA_TILES_AND_STONES", label: "Krishna Tiles And Stones" },
  { value: "GANESHA_TILES_AND_STONES", label: "Ganesha Tiles And Stones" },
  { value: "TERRACOTTA_CLAY_JALI", label: "Terracotta Clay Jali" },
  { value: "LIMESTONE_TILES", label: "Limestone Tiles" },
  { value: "NANO_POLISHED", label: "Nano Polished" },
  { value: "BRICK_TILES", label: "Brick Tiles" },
  { value: "STEPTEST", label: "Step Test" },
  { value: "T15MM_VITRIFIED_TILES", label: "15mm Vitrified Tiles" },
  { value: "SOLID_COLOR_TILES", label: "Solid Color Tiles" },
  { value: "PASTEL_COLOR_TILES", label: "Pastel Color Tiles" },
  { value: "CERAMIC_TILE", label: "Ceramic Tile" },
  { value: "PORCELAIN_TILE", label: "Porcelain Tile" },
  { value: "VITRIFIED_TILES", label: "Vitrified Tiles" },
  { value: "SPIRITUAL_THEME_POOJA_ROOM_TILES", label: "Spiritual Theme Pooja Room Tiles" },
  { value: "MONOCHROME_TILES", label: "Monochrome Tiles" },
  { value: "ABSTRACT_TILES", label: "Abstract Tiles" },
  { value: "HIGHLIGHTER_TILES", label: "Highlighter Tiles" },
  { value: "FULL_BODY", label: "Full Body" },
  { value: "FULL_BODY_STEP", label: "Full Body Step" },
  { value: "FULL_BODY_VITRIFIED", label: "Full Body Vitrified" },
  { value: "BUDDHA_TILES_AND_STONES", label: "Buddha Tiles And Stones" },
  { value: "THIRD_FIRE_VITRIFIED_TILES", label: "Third Fire Vitrified Tiles" },
  { value: "CHARCOAL_PANELS", label: "Charcoal Panels" },
  { value: "FLUTED_WALL_CEILING_PANELS", label: "Fluted Wall Ceiling Panels" },
  { value: "BOTTOCHINO_TILES", label: "Bottochino Tiles" },
  { value: "MULTI_COLOUR_TILES", label: "Multi Colour Tiles" },
  { value: "DHOLPURI_TILES", label: "Dholpuri Tiles" },
  { value: "BOOKMATCH_TILES", label: "Bookmatch Tiles" },
  { value: "WOODEN_TILES", label: "Wooden Tiles" },
  { value: "WOODEN_WALL_TILES", label: "Wooden Wall Tiles" },
  { value: "CARRARA_TILES", label: "Carrara Tiles" },
  { value: "BLUE_POTTERY_TILES", label: "Blue Pottery Tiles" },
  { value: "CARPET_RANGOLI_TILES", label: "Carpet Rangoli Tiles" },
  { value: "TROPICAL_TILES", label: "Tropical Tiles" },
  { value: "MOROCCAN_TILES", label: "Moroccan Tiles" },
  { value: "METALLIC_TILES", label: "Metallic Tiles" },
  { value: "MODULAR_RUSTIC", label: "Modular Rustic" },
  { value: "WOODEN_FLOOR_TILES", label: "Wooden Floor Tiles" },
  { value: "IMPORTED_TILES", label: "Imported Tiles" },
  { value: "HEXAGON_TILES", label: "Hexagon Tiles" },
  { value: "FLUTED_TILE", label: "Fluted Tile" },
  { value: "LOUVER_PANELS", label: "Louver Panels" },
  { value: "NATURAL_STONE_CLADDING", label: "Natural Stone Cladding" },
  { value: "NATURAL_STONE_MURAL", label: "Natural Stone Mural" },
  { value: "OCTAGON_TILES", label: "Octagon Tiles" },
  { value: "PLAIN_PARKING_TILE", label: "Plain Parking Tile" },
  { value: "DIGITAL_PARKING_TILE", label: "Digital Parking Tile" },
];

export const TILE_FINISHES = [
  { value: "GLASS", label: "Glass" },
  { value: "LAPPATO", label: "Lappato" },
  { value: "SUGAR", label: "Sugar" },
  { value: "GLOSSY", label: "Glossy" },
  { value: "CARVING_TILES", label: "Carving Tiles" },
  { value: "METALIC", label: "Metallic" },
  { value: "MATTE", label: "Matte" },
  { value: "SATIN", label: "Satin" },
  { value: "RUSTIC", label: "Rustic" },
  { value: "HI_GLOSSY", label: "Hi Glossy" },
];

export const TILE_COLORS = [
  { value: "YELLOW", label: "Yellow" },
  { value: "WHITE", label: "White" },
  { value: "BLACK", label: "Black" },
  { value: "GRAY", label: "Gray" },
  { value: "GREEN", label: "Green" },
  { value: "IVORY", label: "Ivory" },
  { value: "BEIGE", label: "Beige" },
  { value: "BLUE", label: "Blue" },
  { value: "BROWN", label: "Brown" },
  { value: "CREAM", label: "Cream" },
];

export const TILE_APPLICATIONS = [
  { value: "LIVING_ROOM", label: "Living Room" },
  { value: "HALL", label: "Hall" },
  { value: "BEDROOM", label: "Bedroom" },
  { value: "KITCHEN", label: "Kitchen" },
  { value: "BATHROOM", label: "Bathroom" },
  { value: "BALCONY", label: "Balcony" },
  { value: "BAR_UNIT", label: "Bar Unit" },
  { value: "PASSAGE", label: "Passage" },
  { value: "FOYER", label: "Foyer" },
  { value: "TV_UNIT", label: "TV Unit" },
];

export const TILE_MATERIALS = [
  { value: "MARBLE_STONE", label: "Marble Stone" },
  { value: "GLASS", label: "Glass" },
  { value: "VITRIFIED", label: "Vitrified" },
  { value: "METAL", label: "Metal" },
  { value: "PORCELAIN", label: "Porcelain" },
  { value: "STEEL", label: "Steel" },
  { value: "CLAY", label: "Clay" },
  { value: "CERAMIC", label: "Ceramic" },
  { value: "WOOD", label: "Wood" },
  { value: "CHARCOAL", label: "Charcoal" },
];

export const TILE_MOUNTS = [
  { value: "WALL", label: "Wall" },
  { value: "FLOOR", label: "Floor" },
  { value: "COUNTERTOP", label: "Countertop" },
];

export const SIZE_UNITS = [
  { value: "mm", label: "mm" },
  { value: "cm", label: "cm" },
  { value: "inch", label: "inch" },
  { value: "ft", label: "ft" },
];